### PR TITLE
Detect module dependencies

### LINKED ISSUE #2: Support image dependencies
In monasca-docker we have `kafka` and `kafka-init`. `kafka-init` depends on `kafka`.

Currently we can't make changes to both within one PR since it will (may?) try to build kafka-init before it builds kafka, and there's no way to enforce build order.

(note that in this case kafka-init's Dockerfile and kafka's build.yml have both been updated to refer to the same new, unpublished version)

### PR DESCRIPTION
**Pull request by kornicameister**
Order the plan to build the dependencies before
the children

Closes #2

### CODE REVIEW

**Comment by timothyb89** [comment]
Thanks for the patch! A few things that come to mind:
 * we'll need to make sure dockerfile-parse supports multistage builds like we use in kibana (unfortunately I suspect it does not...) or at least behaves reasonably rather than crashing
 * dbuild may try to build images in parallel so just ordering them in the input list may not be enough, I think child images will need to be explicitly be built as child plans of their parent (in `build_plan_tree` of `build.py`)
 * like you mentioned in #2, we will need to replace the `FROM ...` in child images with the newly-built parent

Actually, that last point might be more complex... just switching around FROMs could be invalid sometimes. To really do this "right" we'd need to somehow make sure we only swap in e.g. `monasca/python:2` for some images and not `:3`. Not totally sure how we'd go about that short of trying to pull metadata from tags like I'd like to do in monasca/pr-bot#17...

**Comment by kornicameister** [comment]
Are you referring to [this](https://github.com/kornicameister/pr-bot/blob/master/lib/check/docker-git.js#L50) part of the code or maybe [that](https://github.com/kornicameister/pr-bot/blob/master/lib/repository/dockerhub.js#L56). Hard to get a grip there :D

I will try to play around with dbuild here and follow somehow your suggestion.

**Comment by kornicameister** [comment]
If I can be serious, after digging deeper inside **dbuild** I started to feel like this too much for me. Don't get me wrong but I thought it will be a bit simpler. I am leaving my project and I am suppose to work on either simple stuff and complete my open changes. 

Sorry, but I guess I have to call it a day and leave that bit for you to handle ;-(

@matrixik you think you could work on this or is it out of your scope as well ?

**Comment by timothyb89** [comment]
Heh, yeah, that's totally fair. The complexity is a big part of why I haven't touched on it myself (yet, at least). 

I've been thinking more and more that dealing with this build dependencies problem is not really worthwhile on a per-repository basis, to the point that we're just making PRs that change any parent/child modules an error in monasca/monasca-helm#186. From there we can have the pr-bot propose changes automatically, since it has all of the logic for figuring out dependency trees in one place.

**Pull request closed without merging**
